server:
  port: 8080
  servlet:
      context-path: /master-teachers # 开发环境>项目名
#  tomcat:
#    uri-encoding: UTF-8

spring:
  profiles:
#    active: dev
  datasource: # database configuration
    url : jdbc:mysql://johnnyzen.cn:3306/master_teachers?useUnicode=true&characterEncoding=UTF-8
    username : XXXX
    password : XXXXXXXX
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database : MYSQL
    show-sql : true  # 在控制台可以看到SQL语句
    hibernate:
      ddl-auto : update # update create create-drop validate
      naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy
      dialect : org.hibernate.dialect.MySQL5Dialect
      format_sql: true # SQL字段类型转换格式化
  mvc: # SpringMVC
    view: # 定位模板的目录
      prefix: classpath:/templates/ # 模板引擎thymeleaf-默认目录：src/main/resources/templates/
      suffix: .html # 返回页面的默认后缀格式
  devtools:
    restart:
      additional-path: src/main/java #添加哪个目录的文件需要restart
#      exclude: static/**,public/**

# 关闭Application
endpoints:
  shutdown:
    enabled: true #启用shutdown
    sensitive: false #禁用密码验证


##################### 自定义属性
masterteacherspider:
  indexUrl: http://222.197.183.99/TutorList.aspx
requestproperties:
  cacheControl: max-age=0
  connection: keep-alive
  accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
  acceptEncoding: gzip, deflate
  acceptLanguage: zh-CN,zh;q=0.9,en;q=0.8,zh-TW;q=0.7
  cookie: cjvi1wv5endh2be010wwm455
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
